[package]
name = "git-leaf"
version = "0.2.3"
authors = ["Jeremie Veillet <jeremie.veillet@gmail.com>"]

[dependencies]
clap = "2.32.0"
regex = "1.1.0"

[[bin]]
name = "git-leaf"
path = "src/main.rs"
